// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmnhogxieivmncgkgdyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtbmhvZ3hpZWl2bW5jZ2tnZHloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NDk2MTMsImV4cCI6MjA3MTMyNTYxM30.036qs6vK7ay0QAhwiTRNst2jDEeiGMscqhH3M8sHKXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});